import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('easyHub', {
  chooseFolder: (): Promise<string | null> => ipcRenderer.invoke('easyhub:choose-folder'),
  localList: () => ipcRenderer.invoke('easyhub:local-list'),
  localInspect: (path: string) => ipcRenderer.invoke('easyhub:local-inspect', path),
  localConnect: (path: string) => ipcRenderer.invoke('easyhub:local-connect', path),
  localCreate: (path: string, name: string, description: string, isPrivate: boolean) => ipcRenderer.invoke('easyhub:local-create', path, name, description, isPrivate),
  localDownload: (owner: string, name: string, parent: string) => ipcRenderer.invoke('easyhub:local-download', owner, name, parent),
  localStatus: (id: string) => ipcRenderer.invoke('easyhub:local-status', id),
  localPublish: (id: string, message: string) => ipcRenderer.invoke('easyhub:local-publish', id, message),
  localCheckSync: (id: string) => ipcRenderer.invoke('easyhub:local-check-sync', id),
  localSync: (id: string, revision: string | undefined, decisions: unknown[]) => ipcRenderer.invoke('easyhub:local-sync', id, revision, decisions),
  localCancel: () => ipcRenderer.invoke('easyhub:local-cancel'),
  localOpenFolder: (id: string) => ipcRenderer.invoke('easyhub:local-open-folder', id),
  localReadIntroduction: (id: string) => ipcRenderer.invoke('easyhub:local-read-introduction', id),
  localSaveIntroduction: (id: string, expected: string, content: string) => ipcRenderer.invoke('easyhub:local-save-introduction', id, expected, content),
  translateContent: (request: unknown) => ipcRenderer.invoke('easyhub:translate-content', request),
  cancelTranslation: (id: string) => ipcRenderer.invoke('easyhub:cancel-translation', id),
  onTranslationProgress: (callback: (value: unknown) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: unknown): void => callback(value); ipcRenderer.on('easyhub:translation-progress', handler); return (): void => { ipcRenderer.removeListener('easyhub:translation-progress', handler); }; },
  onLocalProgress: (callback: (value: unknown) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: unknown): void => callback(value); ipcRenderer.on('easyhub:local-progress', handler); return (): void => { ipcRenderer.removeListener('easyhub:local-progress', handler); }; },
  onLocalStatus: (callback: (value: unknown) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: unknown): void => callback(value); ipcRenderer.on('easyhub:local-status', handler); return (): void => { ipcRenderer.removeListener('easyhub:local-status', handler); }; },
  minimizeWindow: (): Promise<void> => ipcRenderer.invoke('easyhub:window-minimize'),
  toggleMaximizeWindow: (): Promise<void> => ipcRenderer.invoke('easyhub:window-toggle-maximize'),
  closeWindow: (): Promise<void> => ipcRenderer.invoke('easyhub:window-close'),
  openLicense: (): Promise<void> => ipcRenderer.invoke('easyhub:open-license'),
  openExternalLink: (url: string): Promise<void> => ipcRenderer.invoke('easyhub:open-external-link', url),
  authStatus: () => ipcRenderer.invoke('easyhub:auth-status'),
  authStart: () => ipcRenderer.invoke('easyhub:auth-start'),
  authPoll: () => ipcRenderer.invoke('easyhub:auth-poll'),
  authCancel: () => ipcRenderer.invoke('easyhub:auth-cancel'),
  authLogout: () => ipcRenderer.invoke('easyhub:auth-logout'),
  chooseReleaseFiles: (inline: boolean) => ipcRenderer.invoke('easyhub:release-choose-files', inline),
  publishRelease: (input: unknown) => ipcRenderer.invoke('easyhub:release-publish', input),
  cancelRelease: () => ipcRenderer.invoke('easyhub:release-cancel'),
  onReleaseProgress: (callback: (value: unknown) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: unknown): void => callback(value); ipcRenderer.on('easyhub:release-progress', handler); return (): void => { ipcRenderer.removeListener('easyhub:release-progress', handler); }; },
  github: (action: string, ...args: unknown[]) => ipcRenderer.invoke('easyhub:github', action, ...args),
  cancelGithubReads: () => ipcRenderer.invoke('easyhub:github-cancel'),
  downloadArchive: (owner: string, repo: string, ref: string) => ipcRenderer.invoke('easyhub:download-archive', owner, repo, ref),
  downloadReleaseAsset: (owner: string, repo: string, assetId: number) => ipcRenderer.invoke('easyhub:download-release-asset', owner, repo, assetId),
  revealDownloadedArchive: (path: string) => ipcRenderer.invoke('easyhub:reveal-downloaded-archive', path),
  openDownloadedFile: (path: string) => ipcRenderer.invoke('easyhub:open-downloaded-file', path),
  cancelArchive: () => ipcRenderer.invoke('easyhub:cancel-archive'),
  onArchiveProgress: (callback: (value: number) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: number): void => callback(value); ipcRenderer.on('easyhub:archive-progress', handler); return (): void => { ipcRenderer.removeListener('easyhub:archive-progress', handler); }; },
  onDownloadProgress: (callback: (value: { loaded: number; total: number | null; percent: number | null }) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: { loaded: number; total: number | null; percent: number | null }): void => callback(value); ipcRenderer.on('easyhub:download-progress', handler); return (): void => { ipcRenderer.removeListener('easyhub:download-progress', handler); }; },
});
