import { contextBridge, ipcRenderer } from 'electron';
import { isMenuCommand, type MenuCommand, type MenuState } from '../shared/applicationMenu';
import type { DownloadCommand, DownloadItem, DownloadRequest } from '../downloads';
import type { LocalPublishSelection } from '@easyhub/types';

contextBridge.exposeInMainWorld('easyHub', {
  platform: process.platform,
  setMenuState: (state: MenuState): Promise<void> => ipcRenderer.invoke('easyhub:menu-state', state),
  onMenuCommand: (callback: (command: MenuCommand) => void) => {
    const handler = (_event: Electron.IpcRendererEvent, command: unknown): void => {
      if (isMenuCommand(command)) callback(command);
    };
    ipcRenderer.on('easyhub:menu-command', handler);
    return (): void => { ipcRenderer.removeListener('easyhub:menu-command', handler); };
  },
  macProxy: {
    status: () => ipcRenderer.invoke('easyhub:mac-proxy-status'),
    setEnabled: (enabled: boolean) => ipcRenderer.invoke('easyhub:mac-proxy-set-enabled', enabled),
    probe: () => ipcRenderer.invoke('easyhub:mac-proxy-probe'),
    openSettings: () => ipcRenderer.invoke('easyhub:mac-proxy-open-settings'),
    onChanged: (callback: (value: unknown) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: unknown): void => callback(value); ipcRenderer.on('easyhub:mac-proxy-changed', handler); return (): void => { ipcRenderer.removeListener('easyhub:mac-proxy-changed', handler); }; },
  },
  copyPairingCode: (code: string): Promise<boolean> => ipcRenderer.invoke('easyhub:copy-pairing-code', code),
  downloadsList: () => ipcRenderer.invoke('easyhub:downloads-list'),
  downloadsEnqueue: (request: DownloadRequest) => ipcRenderer.invoke('easyhub:downloads-enqueue', request),
  downloadsCommand: (id: string, command: DownloadCommand) => ipcRenderer.invoke('easyhub:downloads-command', id, command),
  downloadsClear: () => ipcRenderer.invoke('easyhub:downloads-clear'),
  downloadsOpen: (id: string, folder: boolean) => ipcRenderer.invoke('easyhub:downloads-open', id, folder),
  onDownloadsChanged: (callback: (items: DownloadItem[]) => void) => { const handler = (_event: Electron.IpcRendererEvent, items: DownloadItem[]): void => callback(items); ipcRenderer.on('easyhub:downloads-changed', handler); return (): void => { ipcRenderer.removeListener('easyhub:downloads-changed', handler); }; },
  chooseFolder: (): Promise<string | null> => ipcRenderer.invoke('easyhub:choose-folder'),
  localList: () => ipcRenderer.invoke('easyhub:local-list'),
  localDiscoveryRoots: () => ipcRenderer.invoke('easyhub:local-discovery-roots'),
  localDiscoveryAddRoot: (path: string) => ipcRenderer.invoke('easyhub:local-discovery-add-root', path),
  localDiscoveryRemoveRoot: (path: string) => ipcRenderer.invoke('easyhub:local-discovery-remove-root', path),
  localDiscoveryScan: () => ipcRenderer.invoke('easyhub:local-discovery-scan'),
  localInspect: (path: string) => ipcRenderer.invoke('easyhub:local-inspect', path),
  localConnect: (path: string) => ipcRenderer.invoke('easyhub:local-connect', path),
  localCreate: (path: string, name: string, description: string, isPrivate: boolean) => ipcRenderer.invoke('easyhub:local-create', path, name, description, isPrivate),
  localDownload: (owner: string, name: string, parent: string) => ipcRenderer.invoke('easyhub:local-download', owner, name, parent),
  localStatus: (id: string) => ipcRenderer.invoke('easyhub:local-status', id),
  localPreviewChanges: (id: string) => ipcRenderer.invoke('easyhub:local-preview-changes', id),
  localFileDiff: (id: string, path: string, snapshot: string) => ipcRenderer.invoke('easyhub:local-file-diff', id, path, snapshot),
  localCancelPreview: (id: string) => ipcRenderer.invoke('easyhub:local-cancel-preview', id),
  localPublish: (id: string, message: string, selection?: LocalPublishSelection) => ipcRenderer.invoke('easyhub:local-publish', id, message, selection),
  localCheckSync: (id: string) => ipcRenderer.invoke('easyhub:local-check-sync', id),
  localSync: (id: string, revision: string | undefined, decisions: unknown[]) => ipcRenderer.invoke('easyhub:local-sync', id, revision, decisions),
  localCancel: () => ipcRenderer.invoke('easyhub:local-cancel'),
  localOpenFolder: (id: string) => ipcRenderer.invoke('easyhub:local-open-folder', id),
  localReadIntroduction: (id: string) => ipcRenderer.invoke('easyhub:local-read-introduction', id),
  localSaveIntroduction: (id: string, expected: string, content: string) => ipcRenderer.invoke('easyhub:local-save-introduction', id, expected, content),
  translateContent: (request: unknown) => ipcRenderer.invoke('easyhub:translate-content', request),
  cancelTranslation: (id: string) => ipcRenderer.invoke('easyhub:cancel-translation', id),
  onTranslationProgress: (callback: (value: unknown) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: unknown): void => callback(value); ipcRenderer.on('easyhub:translation-progress', handler); return (): void => { ipcRenderer.removeListener('easyhub:translation-progress', handler); }; },
  onLocalProgress: (callback: (value: unknown) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: unknown): void => callback(value); ipcRenderer.on('easyhub:local-progress', handler); return (): void => { ipcRenderer.removeListener('easyhub:local-progress', handler); }; },
  onLocalStatus: (callback: (value: unknown) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: unknown): void => callback(value); ipcRenderer.on('easyhub:local-status', handler); return (): void => { ipcRenderer.removeListener('easyhub:local-status', handler); }; },
  minimizeWindow: (): Promise<void> => ipcRenderer.invoke('easyhub:window-minimize'),
  setWindowControlStyle: (style: 'windows' | 'reference', density?: 'comfortable' | 'compact'): Promise<void> => ipcRenderer.invoke('easyhub:window-set-style', style, density),
  toggleMaximizeWindow: (): Promise<void> => ipcRenderer.invoke('easyhub:window-toggle-maximize'),
  closeWindow: (): Promise<void> => ipcRenderer.invoke('easyhub:window-close'),
  openLicense: (): Promise<void> => ipcRenderer.invoke('easyhub:open-license'),
  hostsStatus: () => ipcRenderer.invoke('easyhub:hosts-status'),
  hostsSetEnabled: (enabled: boolean) => ipcRenderer.invoke('easyhub:hosts-set-enabled', enabled),
  hostsRefresh: () => ipcRenderer.invoke('easyhub:hosts-refresh'),
  githubProxyStatus: () => ipcRenderer.invoke('easyhub:github-proxy-status'),
  githubProxySetEnabled: (enabled: boolean) => ipcRenderer.invoke('easyhub:github-proxy-set-enabled', enabled),
  githubProxyRefresh: () => ipcRenderer.invoke('easyhub:github-proxy-refresh'),
  githubProxyCancel: () => ipcRenderer.invoke('easyhub:github-proxy-cancel'),
  openExternalLink: (url: string): Promise<void> => ipcRenderer.invoke('easyhub:open-external-link', url),
  authStatus: () => ipcRenderer.invoke('easyhub:auth-status'),
  aiSettings: () => ipcRenderer.invoke('easyhub:ai-settings'),
  aiSaveSettings: (input: unknown) => ipcRenderer.invoke('easyhub:ai-save-settings', input),
  aiForgetKey: () => ipcRenderer.invoke('easyhub:ai-forget-key'),
  aiTestConnection: () => ipcRenderer.invoke('easyhub:ai-test-connection'),
  aiReviewPull: (input: unknown) => ipcRenderer.invoke('easyhub:ai-review-pull', input),
  aiExplainCode: (input: unknown) => ipcRenderer.invoke('easyhub:ai-explain-code', input),
  aiCancelReview: (id: string) => ipcRenderer.invoke('easyhub:ai-cancel-review', id),
  binaryAnalysisStatus: () => ipcRenderer.invoke('easyhub:binary-analysis-status'),
  binaryAnalysisInstall: (id: string) => ipcRenderer.invoke('easyhub:binary-analysis-install', id),
  binaryAnalysisChooseFile: () => ipcRenderer.invoke('easyhub:binary-analysis-choose-file'),
  binaryAnalyze: (input: unknown) => ipcRenderer.invoke('easyhub:binary-analyze', input),
  binaryAnalysisCancel: (id: string) => ipcRenderer.invoke('easyhub:binary-analysis-cancel', id),
  binaryAiReview: (input: unknown) => ipcRenderer.invoke('easyhub:binary-ai-review', input),
  onBinaryAnalysisProgress: (callback: (value: unknown) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: unknown): void => callback(value); ipcRenderer.on('easyhub:binary-analysis-progress', handler); return (): void => { ipcRenderer.removeListener('easyhub:binary-analysis-progress', handler); }; },
  onAiReviewProgress: (callback: (value: unknown) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: unknown): void => callback(value); ipcRenderer.on('easyhub:ai-review-progress', handler); return (): void => { ipcRenderer.removeListener('easyhub:ai-review-progress', handler); }; },
  authStart: () => ipcRenderer.invoke('easyhub:auth-start'),
  authStartDeletion: (owner: string, repo: string, id: number) => ipcRenderer.invoke('easyhub:auth-start-delete', owner, repo, id),
  authPoll: () => ipcRenderer.invoke('easyhub:auth-poll'),
  authCancel: () => ipcRenderer.invoke('easyhub:auth-cancel'),
  authLogout: () => ipcRenderer.invoke('easyhub:auth-logout'),
  chooseReleaseFiles: (inline: boolean) => ipcRenderer.invoke('easyhub:release-choose-files', inline),
  publishRelease: (input: unknown) => ipcRenderer.invoke('easyhub:release-publish', input),
  editRelease: (input: unknown) => ipcRenderer.invoke('easyhub:release-edit', input),
  addReleaseAssets: (input: unknown) => ipcRenderer.invoke('easyhub:release-add-assets', input),
  removeReleaseAsset: (input: unknown) => ipcRenderer.invoke('easyhub:release-remove-asset', input),
  cancelRelease: () => ipcRenderer.invoke('easyhub:release-cancel'),
  onReleaseProgress: (callback: (value: unknown) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: unknown): void => callback(value); ipcRenderer.on('easyhub:release-progress', handler); return (): void => { ipcRenderer.removeListener('easyhub:release-progress', handler); }; },
  github: (action: string, ...args: unknown[]) => ipcRenderer.invoke('easyhub:github', action, ...args),
  cancelGithubReads: () => ipcRenderer.invoke('easyhub:github-cancel'),
  downloadArchive: (owner: string, repo: string, ref: string) => ipcRenderer.invoke('easyhub:download-archive', owner, repo, ref),
  downloadReleaseAsset: (owner: string, repo: string, assetId: number) => ipcRenderer.invoke('easyhub:download-release-asset', owner, repo, assetId),
  downloadPullRequestFile: (owner: string, repo: string, number: number, path: string, headSha: string) => ipcRenderer.invoke('easyhub:download-pull-file', owner, repo, number, path, headSha),
  revealDownloadedArchive: (path: string) => ipcRenderer.invoke('easyhub:reveal-downloaded-archive', path),
  openDownloadedFile: (path: string) => ipcRenderer.invoke('easyhub:open-downloaded-file', path),
  cancelArchive: () => ipcRenderer.invoke('easyhub:cancel-archive'),
  onArchiveProgress: (callback: (value: number) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: number): void => callback(value); ipcRenderer.on('easyhub:archive-progress', handler); return (): void => { ipcRenderer.removeListener('easyhub:archive-progress', handler); }; },
  onDownloadProgress: (callback: (value: { loaded: number; total: number | null; percent: number | null }) => void) => { const handler = (_event: Electron.IpcRendererEvent, value: { loaded: number; total: number | null; percent: number | null }): void => callback(value); ipcRenderer.on('easyhub:download-progress', handler); return (): void => { ipcRenderer.removeListener('easyhub:download-progress', handler); }; },
});
