import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { createServer } from 'node:http';
import { _electron as electron } from 'playwright-core';
import electronPath from 'electron';

const packaged = process.argv.includes('--packaged');
const imageServer = createServer((_request, response) => {
  response.writeHead(200, { 'Content-Type': 'image/png' });
  response.end(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGP4z8DwHwAFAAH/iZk9HQAAAABJRU5ErkJggg==', 'base64'));
});
await new Promise((resolve) => imageServer.listen(0, '127.0.0.1', resolve));
const imageUrl = `http://127.0.0.1:${imageServer.address().port}/intro.png`;
const packagedExecutable = join(process.cwd(), 'release/win-unpacked/EasyHub.exe');
const app = await electron.launch({
  executablePath: packaged ? packagedExecutable : electronPath,
  args: packaged ? [] : ['.'],
  cwd: process.cwd(),
});
try {
  await app.evaluate(({ dialog, ipcMain }, path) => {
    dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] });
    ipcMain.removeHandler('easyhub:auth-status');
    ipcMain.handle('easyhub:auth-status', () => ({ user: null, clientId: null }));
  }, process.cwd());

  const page = await app.firstWindow();
  const security = await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]?.webContents.getLastWebPreferences());
  assert.equal(security?.contextIsolation, true);
  assert.equal(security?.nodeIntegration, false);
  assert.equal(security?.sandbox, true);
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined');
  assert.equal(await page.evaluate(() => typeof window.easyHub?.openLicense), 'function');
  assert.equal(await page.evaluate(() => typeof window.easyHub?.authStatus), 'function');
  assert.equal('clientId' in (await page.evaluate(() => window.easyHub?.authStatus())), true);
  assert.equal(await page.locator('.app-shell h1').first().evaluate((element) => getComputedStyle(element).userSelect), 'none');
  const iconPath = packaged ? join(process.cwd(), 'release/win-unpacked/resources/easyhub.ico') : join(process.cwd(), 'resources/easyhub.ico');
  assert.equal(await app.evaluate(({ nativeImage }, path) => nativeImage.createFromPath(path).isEmpty(), iconPath), false);
  const licensePath = packaged ? join(process.cwd(), 'release/win-unpacked/resources/LICENSE') : join(process.cwd(), '../../LICENSE');
  assert.equal(existsSync(licensePath), true);
  await page.evaluate(() => {
    window.localStorage.removeItem('easyhub:window-control-style');
    window.localStorage.removeItem('easyhub:language');
  });
  await page.reload();
  await page.locator('.topbar-windows .windows-window-controls').waitFor();
  await page.getByRole('button', { name: '选择语言' }).click();
  await page.getByRole('button', { name: 'English' }).click();
  await page.locator('.sidebar-nav').getByRole('button', { name: 'Home' }).waitFor();
  await page.reload();
  await page.locator('.sidebar-nav').getByRole('button', { name: 'Home' }).waitFor();
  assert.equal(await page.evaluate(() => window.localStorage.getItem('easyhub:language')), 'en');
  await page.screenshot({ path: 'out/home-english-smoke.png' });
  const assertEnglish = async (label) => {
    const remaining = await page.evaluate(() => {
      const walker = document.createTreeWalker(document.querySelector('.app-shell'), NodeFilter.SHOW_TEXT);
      const found = new Set();
      while (walker.nextNode()) {
        if (walker.currentNode.parentElement?.closest('textarea')) continue;
        const value = walker.currentNode.textContent?.trim();
        if (value && /[\u3400-\u9fff]/u.test(value)) found.add(value);
      }
      return [...found];
    });
    assert.deepEqual(remaining, [], `Untranslated text on ${label}`);
  };
  await assertEnglish('Home');
  await page.locator('.sidebar-nav').getByRole('button', { name: 'My Projects' }).click();
  await assertEnglish('Projects');
  await page.getByRole('button', { name: 'New Project' }).first().click();
  await assertEnglish('New Project');
  await page.locator('.sidebar-nav').getByRole('button', { name: 'My Projects' }).click();
  await page.locator('.project-card .plain-heading').first().click();
  await assertEnglish('Project Details');
  await page.getByRole('button', { name: 'Edit Introduction' }).click();
  await assertEnglish('Introduction Editor');
  await page.getByRole('button', { name: 'Preview', exact: true }).click();
  await assertEnglish('Introduction Preview');
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel' }).click();
  await page.locator('.danger-zone-row').first().getByRole('button', { name: 'Change visibility' }).click();
  await assertEnglish('Danger Confirmation');
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel' }).click();
  await page.locator('.detail-primary .panel').nth(1).getByRole('button', { name: 'Publish Source' }).click();
  await page.getByText('Save everyday source changes to GitHub.', { exact: false }).waitFor();
  await assertEnglish('Publish Source');
  await page.getByRole('button', { name: 'Back to Project' }).click();
  await page.locator('.detail-actions').getByRole('button', { name: 'Publish New Release' }).click();
  await assertEnglish('Release Editor');
  await page.getByRole('textbox', { name: 'Release Description' }).fill('A new installer is ready.');
  await page.getByRole('button', { name: 'Preview Release' }).click();
  await assertEnglish('Release Preview');
  await page.getByRole('button', { name: 'Confirm Release' }).click();
  await page.getByRole('heading', { name: 'Published Release' }).waitFor();
  await assertEnglish('Published Release');
  await page.locator('.sidebar-nav').getByRole('button', { name: 'My Projects' }).click();
  await page.locator('.project-card .plain-heading').first().click();
  await page.locator('.detail-side .side-panel').first().getByRole('button', { name: 'View Issues' }).click();
  assert.equal(await page.locator('.issue-project-header').first().getAttribute('aria-expanded'), 'true');
  await page.locator('.sidebar-nav').getByRole('button', { name: 'My Projects' }).click();
  await page.locator('.project-card .plain-heading').first().click();
  await page.locator('.detail-primary .panel').nth(2).locator('.text-link').click();
  await assertEnglish('Version History');
  await page.locator('.history-row').first().click();
  await assertEnglish('Version Details');
  await page.locator('.sidebar-nav').getByRole('button', { name: 'Issues' }).click();
  await assertEnglish('Issues');
  await page.screenshot({ path: 'out/issues-grouped-smoke.png' });
  assert.equal(await page.locator('.issue-project-header').first().getAttribute('aria-expanded'), 'false');
  assert.equal(await page.locator('.issue-row').count(), 0);
  await page.locator('.issue-project-header').first().click();
  assert.equal(await page.locator('.issue-project-header').first().getAttribute('aria-expanded'), 'true');
  await page.locator('.issue-project-header').first().click();
  assert.equal(await page.locator('.issue-row').count(), 0);
  await page.locator('.issue-project-header').first().click();
  await assertEnglish('Expanded Issues');
  await page.locator('.issue-row').first().click();
  await assertEnglish('Issue Details');
  await page.locator('.sidebar-nav').getByRole('button', { name: 'Home' }).click();
  await page.locator('.home-publish-detail').click();
  await assertEnglish('Publish');
  await page.locator('.sidebar-nav').getByRole('button', { name: 'Home' }).click();
  await page.locator('.home-shortcuts button').first().click();
  await assertEnglish('Download');
  await page.locator('.sidebar-nav').getByRole('button', { name: 'Home' }).click();
  await page.locator('.home-shortcuts button').nth(1).click();
  await assertEnglish('Add Folder');
  await page.locator('.sidebar-nav').getByRole('button', { name: 'Settings' }).click();
  await assertEnglish('Settings');
  await page.getByText('GNU GPLv3').waitFor();
  await page.screenshot({ path: 'out/settings-english-smoke.png' });
  await page.getByRole('button', { name: 'Choose language' }).click();
  await page.getByRole('button', { name: '中文' }).click();
  await page.getByRole('button', { name: '选择语言' }).waitFor();
  await page.locator('.topbar-brand').click();
  await page.locator('button[aria-label="设置"]').click();
  assert.equal(await page.locator('.window-style-option').first().getAttribute('aria-pressed'), 'true');
  await page.locator('.window-style-option').nth(1).click();
  await page.locator('.topbar-reference .window-controls').waitFor();
  await page.reload();
  await page.locator('.topbar-reference .window-controls').waitFor();
  assert.equal(await page.evaluate(() => window.localStorage.getItem('easyhub:window-control-style')), 'reference');
  await page.locator('button[aria-label="设置"]').click();
  await page.locator('.window-style-option').first().click();
  await page.locator('.topbar-windows .windows-window-controls').waitFor();
  await page.locator('.topbar-brand').click();
  await page.getByRole('heading', { name: /早上好/ }).waitFor();
  assert.equal(await page.locator('.mascot-plant').evaluate((image) => image instanceof HTMLImageElement && image.complete && image.naturalWidth > 0), true);
  await page.getByRole('button', { name: '关闭窗口' }).waitFor();
  await page.getByRole('button', { name: '最大化或还原窗口' }).click();
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]?.isMaximized()), true);
  await page.getByRole('button', { name: '最大化或还原窗口' }).click();
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]?.isMaximized()), false);
  await page.getByRole('button', { name: '最小化窗口' }).click();
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]?.isMinimized()), true);
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]?.restore());
  await page.setViewportSize({ width: 1060, height: 700 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), true);
  assert.equal(await page.locator('.main-column').evaluate((element) => getComputedStyle(element).scrollbarWidth), 'none');
  await page.getByRole('button', { name: '向下滚动' }).click();
  await page.waitForFunction(() => (document.querySelector('.main-column')?.scrollTop ?? 0) > 0);
  await page.locator('.main-column').evaluate((element) => element.scrollTo(0, element.scrollHeight));
  await page.getByRole('button', { name: '向下滚动' }).waitFor({ state: 'hidden' });
  await page.locator('.main-column').evaluate((element) => element.scrollTo(0, 0));
  await page.getByRole('button', { name: '向下滚动' }).waitFor();
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.screenshot({ path: 'out/home-smoke.png' });
  await page.locator('#home-update-message').fill('整理首页布局');
  await page.locator('.home-publish').getByRole('button', { name: '发布更新' }).click();
  await page.getByText('目前没有尚未发布的修改').waitFor();
  await page.getByRole('button', { name: '新建项目' }).first().click();
  await page.getByPlaceholder('例如：我的工具').fill('点击验收项目');
  await page.getByPlaceholder('用一句话介绍你的项目').fill('测试完整交互');
  await page.getByRole('button', { name: '选择文件夹' }).click();
  await page.getByRole('button', { name: '创建项目' }).click();
  await page.locator('.detail-hero').getByRole('heading', { name: '点击验收项目' }).waitFor();
  await page.getByRole('button', { name: '模拟文件修改' }).click();
  await page.getByText('有 3 个文件还没发布').first().waitFor();
  await page.getByRole('button', { name: '编辑介绍' }).click();
  await page.getByRole('textbox', { name: '项目介绍内容' }).fill('# 点击验收项目\n\n这是新的项目介绍。\n\n- 易于使用');
  await page.getByRole('dialog').getByRole('button', { name: '添加图片' }).click();
  await page.getByRole('textbox', { name: '图片说明' }).fill('界面截图');
  await page.getByRole('textbox', { name: '图片地址' }).fill(imageUrl);
  await page.getByRole('button', { name: '插入', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: '添加链接' }).click();
  await page.getByRole('textbox', { name: '显示文字' }).fill('使用说明');
  await page.getByRole('textbox', { name: '链接地址' }).fill('https://example.com/guide');
  await page.getByRole('button', { name: '插入', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: '预览' }).click();
  await page.getByRole('dialog').getByText('这是新的项目介绍。').waitFor();
  await page.getByRole('dialog').locator('.intro-markdown a').getByText('使用说明').waitFor();
  await page.waitForFunction(() => { const image = document.querySelector('.intro-editor-preview img'); return image instanceof HTMLImageElement && image.complete && image.naturalWidth > 0; });
  await page.screenshot({ path: 'out/intro-editor-smoke.png' });
  await page.getByRole('dialog').getByRole('button', { name: '保存介绍' }).click();
  await page.getByText('有 4 个文件还没发布').first().waitFor();
  await page.locator('.detail-actions').getByRole('button', { name: '发布新版本' }).click();
  assert.equal(await page.getByRole('textbox', { name: '版本号' }).inputValue(), 'v0.01');
  const releaseInputTops = await page.locator('.release-fields input').evaluateAll((elements) => elements.map((element) => element.getBoundingClientRect().top));
  assert.ok(Math.abs(releaseInputTops[0] - releaseInputTops[1]) < 2, '版本号和版本名称输入框应该水平对齐');
  await page.getByRole('button', { name: 'Alpha 测试版' }).click();
  assert.equal(await page.getByRole('textbox', { name: '版本号' }).inputValue(), 'alpha0.1');
  await page.getByRole('button', { name: 'Beta 测试版' }).click();
  assert.equal(await page.getByRole('textbox', { name: '版本号' }).inputValue(), 'beta0.1');
  await page.getByRole('button', { name: '正式版' }).click();
  assert.equal(await page.getByRole('textbox', { name: '版本号' }).inputValue(), 'v0.01');
  await page.getByRole('textbox', { name: '版本介绍' }).fill('新增一键安装。');
  await page.getByRole('button', { name: '添加链接' }).click();
  await page.getByPlaceholder('例如：使用说明').fill('使用说明');
  await page.getByRole('textbox', { name: '链接地址' }).fill('https://example.com/guide');
  await page.getByRole('button', { name: '插入' }).click();
  await page.locator('input[aria-label="选择发布文件"]').setInputFiles([
    { name: 'EasyHub-Setup.exe', mimeType: 'application/octet-stream', buffer: Buffer.from('demo-installer') },
    { name: 'EasyHub-portable.zip', mimeType: 'application/zip', buffer: Buffer.from('demo-archive') },
  ]);
  await page.getByRole('button', { name: '添加图片' }).click();
  await page.locator('input[aria-label="选择介绍图片"]').setInputFiles({
    name: 'screen.png', mimeType: 'image/png',
    buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGP4z8DwHwAFAAH/iZk9HQAAAABJRU5ErkJggg==', 'base64'),
  });
  await page.getByRole('button', { name: '预览发布效果' }).click();
  await page.getByRole('heading', { name: '点击验收项目 v0.01' }).waitFor();
  await page.locator('.release-markdown a').getByText('使用说明').waitFor();
  assert.equal(await page.locator('.release-download-row').count(), 3);
  await page.waitForFunction(() => { const image = document.querySelector('.release-markdown img'); return image instanceof HTMLImageElement && image.complete && image.naturalWidth > 0; }, null, { timeout: 5000 });
  await page.screenshot({ path: 'out/release-preview-smoke.png' });
  await page.getByRole('button', { name: '确认发布新版本' }).click();
  await page.getByRole('heading', { name: '已发布的新版本' }).waitFor();
  await page.getByRole('button', { name: '发布下一个版本' }).click();
  assert.equal(await page.getByRole('textbox', { name: '版本号' }).inputValue(), 'v0.02');
  await page.getByRole('button', { name: '返回项目' }).click();
  await page.getByText('有 4 个文件还没发布').first().waitFor();
  await page.getByRole('button', { name: '发布更新' }).click();
  await page.getByPlaceholder('例如：修复窗口缩放问题').fill('修复窗口缩放问题');
  await page.getByRole('button', { name: '发布更新' }).last().click();
  await page.getByRole('heading', { name: '历史版本' }).waitFor();
  await page.getByText('修复窗口缩放问题').first().waitFor();
  await page.getByRole('button', { name: '问题', exact: false }).first().click();
  await page.getByRole('heading', { name: '问题' }).waitFor();
  await page.getByRole('button', { name: '提出问题' }).click();
  await page.getByPlaceholder('一句话概括问题').fill('按钮位置有问题');
  await page.getByRole('button', { name: '创建问题' }).click();
  await page.getByText('按钮位置有问题').waitFor();
  await page.getByText('按钮位置有问题').click();
  await page.getByPlaceholder('说说你的想法或处理进度…').fill('已经收到，会尽快检查。');
  await page.getByRole('button', { name: '发送回复' }).click();
  await page.getByText('已经收到，会尽快检查。').waitFor();
  await page.getByRole('button', { name: '标记为已解决' }).click();
  await page.getByText('已解决').first().waitFor();
  await page.locator('.sidebar-nav').getByRole('button', { name: '我的项目' }).click();
  await page.locator('.project-card').filter({ hasText: '点击验收项目' }).locator('.plain-heading').click();
  await page.locator('.danger-zone').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'out/danger-zone-smoke.png' });
  const confirmDanger = async (name) => {
    const dialog = page.getByRole('dialog');
    assert.equal(await dialog.getByRole('button', { name }).isDisabled(), true);
    await dialog.getByRole('textbox', { name: '确认项目名称' }).fill('点击验收项目');
    await dialog.getByRole('button', { name }).click();
  };
  await page.locator('.danger-zone-row').nth(0).getByRole('button', { name: '改变可见性' }).click();
  await confirmDanger('改变可见性');
  await page.locator('.detail-hero .visibility-label').getByText('所有人').waitFor();
  await page.locator('.danger-zone-row').nth(1).getByRole('button', { name: '禁用分支保护规则' }).click();
  await confirmDanger('禁用分支保护规则');
  await page.locator('.danger-zone-row').nth(1).getByRole('button', { name: '启用分支保护规则' }).waitFor();
  await page.locator('.danger-zone-row').nth(2).getByRole('button', { name: '转交项目' }).click();
  await page.getByRole('dialog').getByRole('textbox', { name: '新所有者' }).fill('new-owner');
  await confirmDanger('转交项目');
  await page.locator('.danger-zone-row').nth(2).getByText('new-owner').waitFor();
  await page.locator('.danger-zone-row').nth(3).getByRole('button', { name: '存档此项目' }).click();
  await confirmDanger('存档此项目');
  await page.locator('.detail-hero .archived-chip').waitFor();
  assert.equal(await page.getByRole('button', { name: '编辑介绍' }).isDisabled(), true);
  assert.equal(await page.locator('.detail-actions').getByRole('button', { name: '模拟文件修改' }).isDisabled(), true);
  await page.locator('.danger-zone-row').nth(3).getByRole('button', { name: '取消存档' }).click();
  await confirmDanger('取消存档');
  await page.locator('.detail-hero .archived-chip').waitFor({ state: 'hidden' });
  await page.locator('.danger-zone-row').nth(4).getByRole('button', { name: '删除此项目' }).click();
  await page.getByRole('dialog').getByRole('button', { name: '取消' }).click();
  await page.locator('.detail-hero').getByRole('heading', { name: '点击验收项目' }).waitFor();
  await page.locator('.danger-zone-row').nth(4).getByRole('button', { name: '删除此项目' }).click();
  await confirmDanger('删除此项目');
  await page.getByRole('heading', { name: '我的项目' }).waitFor();
  assert.equal(await page.locator('.project-card').filter({ hasText: '点击验收项目' }).count(), 0);
  await app.evaluate(({ ipcMain }) => {
    const user = { login: 'demo-user', name: 'Demo User', avatar_url: '', html_url: 'https://github.com/demo-user' };
    const repo = { id: 101, name: 'CloudDemo', full_name: 'demo-user/CloudDemo', description: 'Live API test project', private: true, updated_at: new Date().toISOString(), default_branch: 'main', owner: { login: 'demo-user' }, open_issues_count: 1 };
    const otherRepo = { ...repo, id: 103, name: 'Aardvark', full_name: 'demo-user/Aardvark', open_issues_count: 0 };
    const publicRepo = { ...repo, id: 104, name: 'PublicDemo', full_name: 'another-user/PublicDemo', private: false, owner: { login: 'another-user' }, open_issues_count: 0 };
    const issue = { id: 201, number: 7, title: 'Window bug', body: 'Please fix the window.', state: 'open', created_at: new Date().toISOString(), user: { login: 'visitor' }, comments: 0 };
    let issueState = 'open';
    const commit = { sha: 'a'.repeat(40), commit: { message: 'Fix launch', author: { name: 'demo-user', date: new Date().toISOString() } }, author: { login: 'demo-user' }, stats: { additions: 10, deletions: 2 }, files: [{ filename: 'src/main.ts', status: 'modified' }] };
    ipcMain.removeHandler('easyhub:auth-status');
    ipcMain.handle('easyhub:auth-status', () => ({ user, clientId: 'Ov23lixRW8K0uXzZqwMj' }));
    ipcMain.removeHandler('easyhub:auth-start');
    ipcMain.handle('easyhub:auth-start', () => ({ userCode: 'ABCD-EFGH', verificationUri: 'https://github.com/login/device', expiresAt: Date.now() + 60000, interval: 1 }));
    ipcMain.removeHandler('easyhub:auth-poll');
    ipcMain.handle('easyhub:auth-poll', () => ({ state: 'complete', user }));
    ipcMain.removeHandler('easyhub:open-external-link');
    ipcMain.handle('easyhub:open-external-link', () => undefined);
    ipcMain.removeHandler('easyhub:github');
    ipcMain.handle('easyhub:github', (_event, action, ...args) => {
      if (action === 'repos') return args[0] === 1 ? [otherRepo, repo] : [];
      if (action === 'searchPublicRepos') return args[0] === 'Public' ? [publicRepo] : [];
      if (action === 'readme') return '# CloudDemo\n\nThis is a GitHub introduction.';
      if (action === 'issues') return [{ ...issue, state: issueState }];
      if (action === 'comments') return [];
      if (action === 'commits') return [commit];
      if (action === 'commit') return commit;
      if (action === 'createComment') return { id: 301, body: args[3], created_at: new Date().toISOString(), user: { login: 'demo-user' } };
      if (action === 'updateIssue') { issueState = args[3]; return { ...issue, state: issueState }; }
      if (action === 'createRepo') return { ...repo, id: 102, name: args[0], full_name: `demo-user/${args[0]}`, description: args[1] };
      if (action === 'createIssue') return { ...issue, id: 202, title: args[2], body: args[3] };
      throw new Error(`Unexpected GitHub action: ${action}`);
    });
  });
  await page.locator('.sidebar-nav').getByRole('button', { name: '设置' }).click();
  await page.getByRole('button', { name: '使用 GitHub 登录' }).click();
  await page.getByText('ABCD-EFGH').waitFor();
  await page.locator('.live-connected').waitFor({ timeout: 8000 });
  await app.evaluate(({ ipcMain }) => {
    ipcMain.removeHandler('easyhub:local-list');
    ipcMain.handle('easyhub:local-list', () => [{ id: 'home-local', repositoryId: 101, owner: 'demo-user', name: 'CloudDemo', localPath: 'C:\\Mock\\CloudDemo', lastOpenedAt: new Date().toISOString() }]);
    ipcMain.removeHandler('easyhub:local-status');
    ipcMain.handle('easyhub:local-status', () => ({ files: [{ path: 'src/main.ts', kind: 'modified' }], needsReview: false }));
  });
  await page.evaluate(() => window.localStorage.setItem('easyhub:language', 'zh'));
  await page.reload();
  await page.locator('.live-connected').waitFor();
  await page.locator('.home-hero').waitFor();
  await page.locator('.home-dashboard').waitFor();
  await page.locator('.home-publish').getByText('CloudDemo 有 1 个文件发生变化').waitFor();
  const inspectedFolder = await page.evaluate(async () => {
    const path = await window.easyHub?.chooseFolder();
    return path ? window.easyHub?.localInspect(path) : null;
  });
  assert.equal(inspectedFolder?.state, 'new');
  await page.locator('.topbar-windows .windows-control-button').first().waitFor();
  assert.equal(await page.locator('.topbar-windows .windows-control-button').count(), 3);
  await page.locator('.sidebar-nav').getByRole('button', { name: '我的项目' }).click();
  await page.getByRole('button', { name: '所有公开项目' }).click();
  await page.locator('.toolbar input').fill('Public');
  await page.getByText('another-user/PublicDemo').waitFor();
  await page.getByText('another-user/PublicDemo').click();
  await page.getByRole('heading', { name: 'PublicDemo' }).waitFor();
  await page.locator('.sidebar-nav').getByRole('button', { name: '我的项目' }).click();
  await page.getByRole('button', { name: /我的云端项目/ }).click();
  await page.locator('.toolbar input').fill('');
  await page.locator('.sidebar-nav').getByRole('button', { name: '问题' }).click();
  await page.locator('.live-issue-group').first().getByText('CloudDemo').waitFor();
  assert.equal(await page.locator('.live-issue-group').first().locator('.live-pending-count').textContent(), '1 个待处理的问题');
  assert.equal(await page.locator('.live-issue-group').first().locator('.live-pending-count').evaluate((element) => getComputedStyle(element).color), 'rgb(197, 51, 71)');
  await page.locator('.sidebar-nav').getByRole('button', { name: '我的项目' }).click();
  await page.locator('.cloud-row').filter({ hasText: 'CloudDemo' }).getByRole('button', { name: 'CloudDemo' }).click();
  await page.getByRole('heading', { name: '项目介绍' }).waitFor();
  await page.getByText('This is a GitHub introduction.').waitFor();
  await page.getByRole('button', { name: '查看问题' }).click();
  await page.getByText('Window bug').click();
  await page.getByRole('textbox', { name: '写一条回复' }).fill('We will fix it.');
  await page.getByRole('button', { name: '发送回复' }).click();
  await page.getByText('We will fix it.').waitFor();
  await page.getByRole('button', { name: '标记为已解决' }).click();
  await page.getByText('已解决').first().waitFor();
  await page.locator('.sidebar-nav').getByRole('button', { name: '问题' }).click();
  await page.getByRole('button', { name: /已解决/ }).first().click();
  const resolvedGroup = page.locator('.live-issue-group').filter({ hasText: 'CloudDemo' });
  assert.equal(await resolvedGroup.locator('.issue-project-header').getAttribute('aria-expanded'), 'false');
  await resolvedGroup.locator('.issue-project-header').click();
  await page.getByText('Window bug').waitFor();
  await page.locator('.live-group-items').getByText('Window bug').click();
  await page.getByRole('heading', { name: 'Window bug' }).waitFor({ timeout: 1500 });
  await page.locator('.sidebar-nav').getByRole('button', { name: '我的项目' }).click();
  await page.locator('.cloud-row').filter({ hasText: 'CloudDemo' }).getByRole('button', { name: 'CloudDemo' }).click();
  await page.getByRole('heading', { name: '历史版本' }).waitFor();
  await page.getByRole('button', { name: '查看全部' }).last().click();
  await page.getByText('Fix launch').first().click();
  await page.getByText('src/main.ts').waitFor();
  await page.getByRole('button', { name: '选择语言' }).click();
  await page.getByRole('button', { name: 'English' }).click();
  const untranslatedLive = () => page.evaluate(() => { const walker = document.createTreeWalker(document.querySelector('.live-shell'), NodeFilter.SHOW_TEXT); const found = new Set(); while (walker.nextNode()) { const value = walker.currentNode.textContent?.trim(); if (value && /[\u3400-\u9fff]/u.test(value)) found.add(value); } return [...found]; });
  const residual = await untranslatedLive();
  assert.deepEqual(residual, [], 'Untranslated text in English live version details');
  await page.screenshot({ path: 'out/live-project-smoke.png' });
  for (const name of ['Home', 'My Projects', 'Issues', 'Settings']) { await page.locator('.sidebar-nav').getByRole('button', { name }).click(); assert.deepEqual(await untranslatedLive(), [], `Untranslated text in English live ${name}`); }
  await page.locator('.sidebar-nav').getByRole('button', { name: 'Home' }).click();
  await page.getByRole('button', { name: 'Download from GitHub' }).click();
  assert.deepEqual(await untranslatedLive(), [], 'Untranslated text in English local projects');
  await app.evaluate(({ ipcMain }) => {
    let link = null;
    let published = false;
    let localIntroduction = '# CloudDemo\n\nLocal introduction.';
    const replace = (name, handler) => { ipcMain.removeHandler(`easyhub:${name}`); ipcMain.handle(`easyhub:${name}`, handler); };
    replace('local-list', () => link ? [link] : []);
    replace('local-inspect', (_event, path) => ({ path, state: 'new' }));
    replace('local-create', (_event, path, name) => { link = { id: 'local-1', repositoryId: 999, owner: 'demo-user', name, localPath: path, lastOpenedAt: new Date().toISOString() }; return link; });
    replace('local-status', () => ({ files: published ? [] : [{ path: 'src/main.ts', kind: 'modified' }], needsReview: false }));
    replace('local-check-sync', () => ({ state: 'current', changedFiles: 0, files: [] }));
    replace('local-sync', () => ({ updated: 0 }));
    replace('local-publish', () => { published = true; return { changed: 1 }; });
    replace('local-download', (_event, owner, name, parent) => { link = { id: 'local-2', repositoryId: 101, owner, name, localPath: `${parent}\\${name}`, lastOpenedAt: new Date().toISOString() }; return link; });
    replace('local-read-introduction', () => localIntroduction);
    replace('local-save-introduction', (_event, _id, expected, content) => { if (expected !== localIntroduction) throw new Error('Introduction changed'); localIntroduction = content; });
  });
  await page.evaluate(() => window.localStorage.setItem('easyhub:language', 'zh'));
  await page.reload();
  await page.locator('.live-connected').waitFor();
  await page.locator('.sidebar-nav').getByRole('button', { name: '我的项目' }).click();
  await page.getByRole('button', { name: '新建项目' }).click();
  await page.getByRole('button', { name: '选择文件夹' }).click();
  await page.getByRole('textbox', { name: '项目名称' }).fill('LocalDemo');
  await page.getByRole('button', { name: '创建项目' }).click();
  await page.getByText('LocalDemo 创建成功，文件已发布到 GitHub。').waitFor();
  await page.getByRole('button', { name: '发布源码' }).click();
  await page.getByRole('textbox', { name: '这次改了什么？' }).fill('修复窗口缩放问题');
  await page.getByRole('button', { name: '发布更新' }).click();
  await page.getByText('发布成功，1 个文件已保存到 GitHub。').waitFor();
  await app.evaluate(({ ipcMain }) => {
    globalThis.syncSmokeDecisions = null;
    ipcMain.removeHandler('easyhub:local-check-sync');
    ipcMain.handle('easyhub:local-check-sync', () => ({ state: 'review', remoteRevision: 'a'.repeat(40), changedFiles: 1,
      files: [{ path: 'src/main.ts', mine: 'my version', github: 'GitHub version', previewable: true }] }));
    ipcMain.removeHandler('easyhub:local-sync');
    ipcMain.handle('easyhub:local-sync', (_event, _id, _revision, decisions) => { globalThis.syncSmokeDecisions = decisions; return { updated: 1 }; });
  });
  await page.locator('.local-project-card').filter({ hasText: 'LocalDemo' }).getByRole('button', { name: '获取最新' }).click();
  await page.getByRole('heading', { name: '有内容需要确认' }).waitFor();
  await page.getByRole('button', { name: '查看不同' }).click();
  await page.getByText('GitHub version').waitFor();
  await page.getByRole('button', { name: '保留我的' }).click();
  await page.screenshot({ path: 'out/sync-review-smoke.png' });
  await page.getByRole('button', { name: '确认并获取最新' }).click();
  assert.deepEqual(await app.evaluate(() => globalThis.syncSmokeDecisions), [{ path: 'src/main.ts', choice: 'mine' }]);
  await page.locator('.sidebar-nav').getByRole('button', { name: '我的项目' }).click();
  await page.locator('.cloud-row').filter({ hasText: 'CloudDemo' }).getByRole('button', { name: 'CloudDemo' }).click();
  await page.getByRole('button', { name: '本地项目与发布源码' }).click();
  await page.getByRole('button', { name: '下载', exact: true }).click();
  await page.getByRole('dialog', { name: '下载通知' }).getByText('项目已经下载完成。').waitFor();
  await page.getByRole('button', { name: '关闭下载通知' }).click();
  await page.getByRole('button', { name: '返回', exact: true }).click();
  await page.getByRole('button', { name: '编辑介绍' }).click();
  await page.getByRole('dialog').getByRole('button', { name: '添加图片' }).click();
  await page.getByRole('textbox', { name: '图片地址' }).fill(imageUrl);
  await page.getByRole('button', { name: '插入', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: '添加链接' }).click();
  await page.getByRole('textbox', { name: '链接地址' }).fill('https://example.com/guide');
  await page.getByRole('button', { name: '插入', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: '预览' }).click();
  await page.waitForFunction(() => { const image = document.querySelector('.intro-editor-preview img'); return image instanceof HTMLImageElement && image.complete && image.naturalWidth > 0; });
  await page.getByRole('dialog').locator('.intro-markdown a').waitFor();
  await page.getByRole('checkbox', { name: '我确认替换这个项目的本地介绍文件' }).check();
  await page.getByRole('dialog').getByRole('button', { name: '保存介绍' }).click();
  await page.getByText('介绍已保存到本地，发布源码后同步到 GitHub。').waitFor();
  const closed = page.waitForEvent('close');
  await page.locator('.windows-window-controls button').last().click();
  await closed;
  process.stdout.write(`${packaged ? 'Packaged' : 'Electron'} UI smoke test passed.\n`);
} finally {
  await app.close().catch(() => {});
  imageServer.close();
}
